version: "3.1"

services:
  app:
    image: n4:node-hack
    build:
      context: docker/node
    ports:
      - "8080:80"
    volumes:
      - "./app:/app"
    command: bash -c "npm i && npm run serve"
  